### ISSUE TITLE
Create a Visual Design of the Login Page

### ISSUE THREAD

**Issue by sheel12** [sheel12/CCApp#1]
Finalize log in screen of the user

**Comment by sheel12** [comment]
draft 1 editable link: https://drive.google.com/file/d/0B2wQdIVftgWRR21RWXpUaDNEbzg/view?usp=sharing

**Comment by sheel12** [comment]
![loginscreendraft1](https://user-images.githubusercontent.com/29982411/28496929-557cd004-6f47-11e7-8649-2ce38896cfd3.jpg)

**Comment by dchopra001** [comment]
This looks good. Some comments:

-We'll probably need to left-align the "Username" and "Password" fields
-We should find a different colour scheme. This is too colourful. 

But we can decide on that stuff later and submit a final layout here after.

This is good enough to start.

**Comment by sheel12** [comment]
![loginscreendraft2](https://user-images.githubusercontent.com/29982411/28507626-4f25973e-7002-11e7-8c3c-4f7f7ad9b185.jpg)

**Comment by sheel12** [comment]
--additional feature future improvement phase 2. sign up with Facebook/google

**Comment by sheel12** [comment]
Control Flow of Login screen:

if (user exists and log in correct) 
   go to summary/welcome page
else if (user exists and incorrect login)
   go to login page with message at top of incorrect password
else if(User does not exist)
    go to log in page with message to register
