### ISSUE TITLE
ERDiagram_of_CreditCard_Tracker

### ISSUE THREAD

**Issue by sheel12** [sheel12/CCApp#12]

**Comment by sheel12** [comment]
![erdiagramcc](https://user-images.githubusercontent.com/29982411/28800411-8d7b8eb2-761a-11e7-9948-a868eb9d80c9.jpg)

**Comment by sheel12** [comment]
https://drive.google.com/file/d/0B2wQdIVftgWRYmNYcUZCNU5wclU/view?usp=sharing

**Comment by sheel12** [comment]
Created ER diagram for credit card-editable link is above

**Comment by dchopra001** [comment]
Can you change the title to be more descriptive? See other examples of how I named them.

Also, can you provide a detailed task description in the description field.

**Comment by sheel12** [comment]
Update_cur_bal is ternary relationship.For a certain credit card and Transaction_type, there can be many transactions, but for a given transaction, there can be only one credit card and transaction type. So it is one to Many(Transaction)

**Comment by sheel12** [comment]
OkOn Jul 31, 2017 6:05 PM, Dhruv Chopra <notifications@github.com> wrote:Can you change the title to be more descriptive? See other examples of how I named them.
Also, can you provide a detailed task description in the description field.

**Comment by sheel12** [comment]
new sharable link
https://drive.google.com/file/d/0B2wQdIVftgWRYmNYcUZCNU5wclU/view?usp=sharing

**Comment by sheel12** [comment]
![screen shot 2017-08-15 at 11 44 11 pm](https://user-images.githubusercontent.com/29982411/29346500-c4f46a1c-8213-11e7-8845-cad2adf7ba0c.png)
