### ISSUE TITLE
Create a Visual Design of the Welcome/Summary Page

### ISSUE THREAD

**Issue by sheel12** [sheel12/CCApp#2]
Summary page for balance of all cards. What to display if there is no card entry.

**Comment by dchopra001** [comment]
To add on to the description of this task:

This page will be presented to the user after they first log in. It will display a summary/stats of the current user's total debt. From here they can go on to other screens in the app.

**Comment by dchopra001** [comment]
Some ideas for the screen:

At the top we can have something like: 

_"Welcome <FirstName>, 
Here is your current debt status"_

Then in the centre we can have a box of data like so:

_"Total balance:          <value>
No. of Cards:             <value>
Total min Payments: <value>
etc..."_

**Comment by sheel12** [comment]
WelcomeSummaryPageDraft1.jpg

**Comment by dchopra001** [comment]
The image didn't paste properly...

**Comment by sheel12** [comment]
![welcomesummarypagedraft1](https://user-images.githubusercontent.com/29982411/28508923-431a1cbc-700c-11e7-9c5a-5e30a325a025.jpg)

**Comment by sheel12** [comment]
added it. Now it fits properly

**Comment by dchopra001** [comment]
Can you post the editable link from drawio, so I can make changes

**Comment by dchopra001** [comment]
I think we need to decide on a color scheme so the app looks uniform across all the screens.

**Comment by sheel12** [comment]
YesOn Jul 24, 2017 1:17 AM, Dhruv Chopra <notifications@github.com> wrote:I think we need to decide on a color scheme so the app looks uniform across all the screens.

**Comment by sheel12** [comment]
Editable link as below:
https://drive.google.com/file/d/0B2wQdIVftgWRaTJxVjNaVUgxYUk/view?usp=sharing

**Comment by sheel12** [comment]
Summary Page
a) No cc entered: 
      2-3 words welcome , ex Hello <user name>
      additional message:to start tracking your cc and see your spendings and payments, enter your              credit card information.
b) cc's entered:
     2-3 words welcome as above
     general statistics of all the cc such as number of cards, balance as on today, 
       average monthly payments, minimum monthly payment required, average monthly spendings since start,etc.

**Comment by sheel12** [comment]
Need to remove click for more options and add global menu as header or footer for navigation.
