### ISSUE TITLE
Create a Visual Design of the Main Menu Page

### ISSUE THREAD

**Issue by sheel12** [sheel12/CCApp#3]
Menu page for different options-'New Card','Enter Transaction','Current balance','updating of cards information','Delete' option, 'Any other option to be discussed'

**Comment by dchopra001** [comment]
Test

**Comment by dchopra001** [comment]
Editable Link: https://drive.google.com/file/d/0B-vp0N7ERNmoMDVhZEpkX1VLdWs/view?usp=sharing

**Comment by dchopra001** [comment]
![mainmenudraft1](https://user-images.githubusercontent.com/11260919/28660072-9e4596b4-727f-11e7-856d-8f4c6f9bf05c.jpg)

**Comment by sheel12** [comment]
Heading Main Menu can be replaced with more meaningful one

**Comment by sheel12** [comment]
The above screen will be option for global menu for navigation. We need to add one more menu option -as current balance for a card.
