### ISSUE TITLE
Create a Visual Design of the New Card Entry Page

### ISSUE THREAD

**Issue by sheel12** [sheel12/CCApp#4]
UI for new card entry to be finalized

**Comment by sheel12** [comment]
![newcardentrydraft1](https://user-images.githubusercontent.com/29982411/28545501-2dadc2d2-7095-11e7-8d14-971581f382f0.jpg)

**Comment by sheel12** [comment]
Editable link for above:
https://drive.google.com/file/d/0B2wQdIVftgWRb1ZrNXlYdHRqVTg/view?usp=sharing

**Comment by dchopra001** [comment]
Comments:

The first two boxes look like buttons, but they should be drop-down and text boxes, respectively.

What is the purpose of track start date?

The nominal interest table needs to be reformatted. That table won't fit on a phone screen.

How about something like this: a list of textboxes that have the following values inside as placeholders:

Cash Interest Rate
Current Balance on cash transaction
Purchase interest rate
Current balance on purchase transactions
Balance transfer interest rate
Current t balance on Balance transfers

**Comment by sheel12** [comment]
Track Start Date is the date of first entry of the credit card. It will be used to track monthly payments, calculation of interest and time needed to  complete pay a card

**Comment by dchopra001** [comment]
Shouldn't it be sufficient to ask for when the next monthly payment is due? And then we can calculate everything from there on. We can assume that the tracking starts from the day the user enters their new card into our system.

**Comment by sheel12** [comment]
In the actual app, it will be a drop down box with three transactions as 'cash', 'purchases' and 'balance transfer' and 'other'. An editable text box will be there. So when user clicks on say 'cash', and enters 21 in the edit text box, it is stored in the appropriate table in the data base. If user selects 'other', then another edit text box prompts up wherein user can enter the type of transaction and then in second edit text , he can enter rate of interest

**Comment by sheel12** [comment]
The balance entered here is not current as on today, but will be a one time entry of the opening balance that will never change.

**Comment by dchopra001** [comment]
I'm not sure if this layout works well. For the calculations to be as accurate as possible, we need data on all transaction types. By putting the transaction types in the drop-down , it seems like entering all of them is optional. It's not user friendly of they have to go back and enter a new value into the drop-down in order to record anew type of interest rate and balance. If it all appears in a single list, then they will enter the data as they scroll through the form. This way it seems intuitive as it will feel like they are entering data into a form (like they would on paper).

**Comment by dchopra001** [comment]
You shared the google drive link. Can you share the draw.io link instead?

Edit: Nevermind. I'll open the xml file in draw.io manually

**Comment by dchopra001** [comment]
Here's a revised version (editable link):
https://drive.google.com/file/d/0B2wQdIVftgWRb1ZrNXlYdHRqVTg/view?usp=sharing

**Comment by dchopra001** [comment]
![newcardentrydraft2](https://user-images.githubusercontent.com/11260919/28550868-3175a200-70b2-11e7-8e4b-60d5be246d24.jpg)

**Comment by sheel12** [comment]
where is opening balance

**Comment by dchopra001** [comment]
I forgot about opening balance.but we can add it directly underneath each
type of transaction as another textbox.

**Comment by dchopra001** [comment]
Can you rename this issue to be more descriptive? (See how the first two issues are named)

**Comment by sheel12** [comment]
We need to add a field for statement date

**Comment by sheel12** [comment]
Future addition in UI-option to select if card is active or not

**Comment by sheel12** [comment]
1) Upon submit the information of credit card, the data is securely transmitted to the server. 2) From the DB verify if inserted data is valid or not, returns true if insert is successful otherwise false.
3) example for validation, credit card length, etc.
4)If true is returned on client end, a dialog box is displayed with message that insert successful with an option to go back to summary page or add another card. If user selects add another card then a fresh form for adding card is displayed again.
otherwise, app redirects to summary page.
5) If the server returns false, a dialog box will be displayed indicating insert not successful and with ok button. On clicking ok button the app will go to add a new card form and a string  with appropriate error message for the user  will be displayed on the top of that form. The values previously entered in the form will remain in their respective text fields with field with error highlighted red. 
6)A temporary error message table table is created with two columns-Col 1 is the text box id  and the second column will be  error message. If second column is blank, the text id is correct.
