### ISSUE TITLE
Create a Visual Design of the Enter Transaction Page

### ISSUE THREAD

**Issue by sheel12** [sheel12/CCApp#5]
UI for Enter Transaction to be finalized.

**Comment by dchopra001** [comment]
Editable Link: 
https://drive.google.com/file/d/0B-vp0N7ERNmoLUdMVXBJd2xBaFE/view?usp=sharing

**Comment by dchopra001** [comment]
![screen shot 2017-07-27 at 4 16 51 am](https://user-images.githubusercontent.com/11260919/28660792-75edd1f6-7282-11e7-9cd7-eefa470eff54.png)

**Comment by sheel12** [comment]
On clicking submit, the app is redirected to the summary page
