### ISSUE TITLE
Create a Visual Design of the Update Card Page

### ISSUE THREAD

**Issue by sheel12** [sheel12/CCApp#6]
UI for 'Update Card' info to be finalized

**Comment by sheel12** [comment]
![updatecarddraft1](https://user-images.githubusercontent.com/29982411/28553196-66f510ce-70c0-11e7-910b-f572ddfdf41b.jpg)

**Comment by sheel12** [comment]
Edit link:
https://drive.google.com/file/d/0B2wQdIVftgWRbHBYYXNVU2dvb1E/view?usp=sharing

**Comment by dchopra001** [comment]
This should be organized differently.

The screen should be called 'Enter a new transaction'

There should only be one drop-down on the first screen:
Here the user picks which card to enter the transaction for. 

Then they are presented with the next screen, where there are three buttons and they can only pick one:
1. Purchase
2. Cash Withdrawal
3. Payment

Then they can enter the dollar value in the last screen.

**Comment by dchopra001** [comment]
Can you read through this. We will need this in order to design the color scheme of the app:
https://techcrunch.com/2017/04/06/new-google-tool-helps-developers-pick-the-right-colors-for-their-apps/

**Comment by sheel12** [comment]
This screen is not for entering a transaction. This screen is for making changes to the credit card, like if nominal interest changes (sometimes due to non payment interest becomes 25% instead of 19 %) or if there is another transaction type or when the credit card expires and we get a new card then it's number might change. transaction screen will be separate

**Comment by dchopra001** [comment]
Okay, I think the layout I suggested can still apply, but in a different context. This way the application will seem more user intuitive and we can 'guide' the user to take the necessary steps without giving explicit instructions. Do you agree?

**Comment by sheel12** [comment]
yes you are right. But this we can decide once we make all views. Then will discuss the linkages between various views as a flow diagram. At that point the missing parts can be added or excess parts can be eliminated.

**Comment by dchopra001** [comment]
Please rename this one as well.

**Comment by sheel12** [comment]
1)Make sure, to add submit button
2) On clicking submit button, the app is redirected to summary page
