### ISSUE TITLE
Create a Visual Design of the Delete Card Page

### ISSUE THREAD

**Issue by sheel12** [sheel12/CCApp#7]
UI for 'Delete the card' to be finalized

**Comment by dchopra001** [comment]
Editable Link: https://drive.google.com/file/d/0B-vp0N7ERNmoMFhUX0lZaUVaVkU/view?usp=sharing

**Comment by dchopra001** [comment]
![screen shot 2017-07-27 at 4 19 56 am](https://user-images.githubusercontent.com/11260919/28660906-e009ca18-7282-11e7-85af-5145fc1371a3.png)

**Comment by sheel12** [comment]
1) On clicking submit button, the credit card info will be sent to the server to be deleted.
2)If successful, a dialog box will appear with a message that the credit card is deleted with ok button. on clicking the ok button, the app is redirected to summary page.
3)If unsuccessful, then again a dialog box is displayed indicating delete is unsuccessful with two buttons as exit and try again. on clicking exit, app is redirected to summary page and on clicking try again, delete the card screen is displayed again.
